version: "2"
services:
  postgresql12:
    image: "bitnami/postgresql:12"
    ports:
      - "5000:5432"
    volumes:
      - "postgresql_data_12:/bitnami/postgresql12"
    environment:
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=pwd0123456789
      - POSTGRESQL_DATABASE=my_database
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  postgresql_data_12:
    driver: local
